apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app-service
    owner: Vlad
spec:
  selector:
    project: testapp
  ports:
    - port: 8080
      name: test-app-listener
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer

